import { AppState } from './types';

export const defaultState: AppState = {
  currentDate: '2026-06-29',
  targetDate: '2026-08-06',
  tasks: [
    {
      id: 't1',
      name: '1. 服务列表',
      toolName: 'list_dataservice',
      priority: 'Highest',
      owner: '待定',
      status: 'In Progress',
      progress: 10,
      startDate: '2026-06-29',
      endDate: '2026-07-12',
      weekProgress: '确认服务发现接口范围',
      nextWeekPlan: '冻结返回字段、补充异常场景',
      risk: '',
    },
    {
      id: 't2',
      name: '2. 服务元数据',
      toolName: 'describe_dataservice',
      priority: 'Highest',
      owner: '待定',
      status: 'In Progress',
      progress: 10,
      startDate: '2026-06-29',
      endDate: '2026-07-12',
      weekProgress: '梳理字段、参数、指标、维度描述口径',
      nextWeekPlan: '确认元数据结构是否满足 Agent 参数理解',
      risk: '',
    },
    {
      id: 't3',
      name: '3. 数据查询',
      toolName: 'query_dataservice',
      priority: 'Highest',
      owner: '待定',
      status: 'Not Started',
      progress: 0,
      startDate: '2026-07-13',
      endDate: '2026-07-26',
      weekProgress: '等待接口设计和元数据能力稳定',
      nextWeekPlan: '确认查询参数、权限校验、错误码和返回结构',
      risk: '需重点关注',
    },
    {
      id: 't4',
      name: '4. 维度字段枚举值查询',
      toolName: 'describe_fields_values',
      priority: 'Lower',
      owner: '待定',
      status: 'Not Started',
      progress: 0,
      startDate: '2026-07-27',
      endDate: '2026-08-09',
      weekProgress: '暂不进入主链路开发',
      nextWeekPlan: '待核心查询链路稳定后启动',
      risk: '',
    },
    {
      id: 't5',
      name: '5. 数据查询 Group By',
      toolName: 'query_dataservice.groupBy',
      priority: 'Lowest',
      owner: '待定',
      status: 'Not Started',
      progress: 0,
      startDate: '2026-08-03',
      endDate: '2026-08-09',
      weekProgress: '不作为 8 月 16 日核心交付前置条件',
      nextWeekPlan: '评估是否进入本期交付范围',
      risk: '可延期，不影响主链路',
    },
    {
      id: 't6',
      name: '6. 发布验收',
      toolName: '回归 / 文档 / 演示 / 对外交付',
      priority: 'Release Phase',
      owner: '待定',
      status: 'Not Started',
      progress: 0,
      startDate: '2026-08-10',
      endDate: '2026-08-16',
      weekProgress: '暂无',
      nextWeekPlan: '提前准备接口说明、验收清单和演示样例',
      risk: '取决于核心链路完成情况',
    }
  ],
  meetingRecords: [
    {
      id: 'm1',
      date: '2026-06-29',
      confirmations: [
        { id: 'c1', text: '服务列表 list_dataservice 的接口字段是否冻结', done: false },
        { id: 'c2', text: '服务元数据 describe_dataservice 是否覆盖字段、参数、指标、维度', done: false },
        { id: 'c3', text: '数据查询 query_dataservice 的参数结构是否确定', done: false },
        { id: 'c4', text: '统一接入 MCP 开关是否影响原有使用方式', done: false },
        { id: 'c5', text: '8 月 16 日交付范围是否排除 Group By', done: false }
      ],
      blockers: [],
      decisions: [],
      conclusion: '',
      updatedAt: new Date().toISOString()
    }
  ],
  currentEditingMeetingDate: '2026-06-29'
};
